server:
  port: 82

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/pd_store?useUnicode=true&characterEncoding=UTF-8
        username: ykw
        password: ykw
    data:
        solr:   #注意修改ip地址
            host: http://127.0.0.1:8983/solr/pd
mybatis-plus:
  #typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:com.pd.mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true

logging:
  level: 
    cn.tedu.ssm.mapper: debug
resources: # 指定静态资源的路径
        static-locations: classpath:/
        cache-period: 0
        
